import SwiftUI

extension ClaudeInsights {
    struct ReportView: View {
        let report: String
        let date: Date

        @Environment(\.colorScheme) var colorScheme
        @Environment(AppState.self) var appState
        @State private var showShareSheet = false

        var body: some View {
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    // Header
                    HStack {
                        Image(systemName: "doc.text.fill")
                            .foregroundColor(.purple)
                        Text("Weekly Analysis Report")
                            .font(.headline)
                        Spacer()
                    }

                    Text("Generated: \(date.formatted(date: .long, time: .shortened))")
                        .font(.caption)
                        .foregroundColor(.secondary)

                    Divider()

                    // Report Content
                    Text(report)
                        .font(.body)

                    Divider()

                    // Disclaimer
                    HStack(alignment: .top, spacing: 8) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundColor(.orange)
                        Text("""
                        This report is for educational purposes only and should not replace \
                        professional medical advice. Always consult your healthcare provider \
                        before making changes to your treatment.
                        """)
                        .font(.caption)
                        .foregroundColor(.secondary)
                    }
                    .padding()
                    .background(Color.orange.opacity(0.1))
                    .cornerRadius(8)
                }
                .padding()
            }
            .background(appState.trioBackgroundColor(for: colorScheme))
            .navigationTitle("Report")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button {
                        showShareSheet = true
                    } label: {
                        Image(systemName: "square.and.arrow.up")
                    }
                }
            }
            .sheet(isPresented: $showShareSheet) {
                ShareSheet(activityItems: [formattedReportForSharing])
            }
        }

        private var formattedReportForSharing: String {
            """
            Trio - Claude Insights Weekly Report
            Generated: \(date.formatted(date: .long, time: .shortened))

            \(report)

            ---
            This report was generated by Claude AI based on your Trio diabetes data.
            It is for educational purposes only and should not replace professional medical advice.
            """
        }
    }

    private struct ShareSheet: UIViewControllerRepresentable {
        let activityItems: [Any]

        func makeUIViewController(context: Context) -> UIActivityViewController {
            UIActivityViewController(activityItems: activityItems, applicationActivities: nil)
        }

        func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
    }
}
